#!/usr/bin/env python3
"""
generated.py — Keep the generated symbols/ files current, on demand.

symbols/functions.csv and symbols/progress.json are generated by
tools/progress.py and are not tracked by git (a branch never carries them,
so they never conflict). Every tool that reads them calls ensure() first:
when a file is missing, or anything it is computed from has changed since it
was written, it is regenerated (a few seconds; needs the ROM and asar).

"Computed from" is recorded as a fingerprint in symbols/.generated (also
untracked): every file under asm/, the review log, the readability baseline,
the tools, and the ROM.

    python3 tools/generated.py      regenerate if stale, print what it did
"""

import contextlib
import csv
import hashlib
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROM_PATH = Path('roms/chrono_trigger.sfc')
SYMBOLS = Path('symbols')
FUNCTIONS_CSV = SYMBOLS / 'functions.csv'
PROGRESS_JSON = SYMBOLS / 'progress.json'
STAMP = SYMBOLS / '.generated'
OUTPUTS = (FUNCTIONS_CSV, PROGRESS_JSON)

# Set while tools/progress.py computes the outputs: the function layout
# (address, end, name rows) is known before the lint runs, and the lint's
# caller checks (tools/xref.py) read it from here instead of recursing.
_layout = None


def can_generate() -> bool:
    return ROM_PATH.exists() and shutil.which('asar') is not None


def _inputs() -> list[Path]:
    files = [p for p in Path('asm').rglob('*') if p.is_file()]
    files += [p for p in SYMBOLS.glob('reviews*') if p.is_file()]
    files += [p for p in (SYMBOLS / 'reviews').glob('*') if p.is_file()]
    files += [p for p in Path('tools').glob('*.py')]
    files += [Path('tools/readability_baseline.txt')]
    return sorted(p for p in set(files) if p.exists())


def fingerprint() -> str:
    h = hashlib.sha256()
    for p in _inputs():
        h.update(str(p).encode() + b'\0')
        h.update(hashlib.sha256(p.read_bytes()).digest())
    if ROM_PATH.exists():
        h.update(b'rom\0' + hashlib.sha256(ROM_PATH.read_bytes()).digest())
    return h.hexdigest()


def is_current() -> bool:
    if not all(p.exists() for p in OUTPUTS) or not STAMP.exists():
        return False
    return STAMP.read_text().strip() == fingerprint()


def write_outputs(outputs: dict) -> None:
    """Write generated files and record what they were computed from."""
    SYMBOLS.mkdir(exist_ok=True)
    for path, text in outputs.items():
        path.write_text(text)
    STAMP.write_text(fingerprint() + '\n')


def ensure(quiet: bool = True) -> bool:
    """Regenerate symbols/functions.csv and progress.json if stale.

    Returns True when the files are current afterwards. Without the ROM or
    asar nothing can be generated and it returns whether they happen to be
    current already.
    """
    if _layout is not None:            # inside a generation: nothing to do
        return True
    if is_current():
        return True
    if not can_generate():
        return False
    import progress
    if not quiet:
        print('generated.py: symbols/ is stale or missing; regenerating', file=sys.stderr)
    progress.write_generated(progress.analyse())
    return True


@contextlib.contextmanager
def generating(rows: list[dict]):
    """Within progress.analyse(): publish the layout rows to function_rows()."""
    global _layout
    saved, _layout = _layout, rows
    try:
        yield
    finally:
        _layout = saved


def function_rows() -> list[dict]:
    """Rows of symbols/functions.csv (at least address, end, size, name).

    Regenerates the file first if it is stale. Empty without the ROM.
    """
    if _layout is not None:
        return list(_layout)
    ensure()
    if not FUNCTIONS_CSV.exists():
        return []
    with FUNCTIONS_CSV.open() as f:
        return list(csv.DictReader(f))


def main() -> int:
    if is_current():
        print('symbols/ is current.')
        return 0
    if not can_generate():
        print(f'symbols/ is stale or missing, and it needs {ROM_PATH} and asar to regenerate.')
        return 2
    ensure(quiet=False)
    print('symbols/ regenerated: ' + ', '.join(str(p) for p in OUTPUTS))
    return 0


if __name__ == '__main__':
    sys.exit(main())
